export const GET_PARAMETERS_BY_NAME_REQUEST = 'PARAMETERS/GET_PARAMETERS_BY_NAME_REQUEST';
export const GET_PARAMETERS_BY_NAME_SUCCESS = 'PARAMETERS/GET_PARAMETERS_BY_NAME_SUCCESS';
export const GET_PARAMETERS_BY_NAME_ERROR = 'PARAMETERS/GET_PARAMETERS_BY_NAME_ERROR';
